demo-data:
  name: test

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.111.14.184:3306/spring?characterEncoding=utf8&useUnicode=true&verifyServerCertificate=false&useSSL=false&requireSSL=false
      username: root
      password: "038450"

  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 47.111.14.184
    #    host: localhost
    # Redis服务器连接密码（默认为空）需加双引号不然识别不了
    password: "038450"
    # Redis连接端口号
    port: 6379
    # 超时时间
    timeout: 5000
    lettuce: # 如果使用的jedis 则将lettuce改成jedis即可
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 5